<?php

declare(strict_types=1);

namespace App\Docs\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Get(path: '/api/admin/dashboard', tags: ['Admin'], summary: 'Dashboard admin', security: [['BearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Dashboard admin berhasil diambil', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Dashboard admin berhasil diambil'), new OA\Property(property: 'data', type: 'object')]))])]
#[OA\Get(path: '/api/admin/pengaturan', tags: ['Admin'], summary: 'Ambil pengaturan admin', security: [['BearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Pengaturan admin berhasil diambil', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Pengaturan admin berhasil diambil'), new OA\Property(property: 'data', type: 'object')]))])]
#[OA\Put(path: '/api/admin/pengaturan', tags: ['Admin'], summary: 'Update pengaturan admin', security: [['BearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Pengaturan admin berhasil diubah', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Pengaturan admin berhasil diubah')]))])]
#[OA\Get(path: '/api/admin/users', tags: ['Admin'], summary: 'Daftar user', security: [['BearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Daftar user berhasil diambil', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Daftar user berhasil diambil'), new OA\Property(property: 'data', type: 'array', items: new OA\Items(type: 'object'))]))])]
#[OA\Get(path: '/api/admin/users/{id}', tags: ['Admin'], summary: 'Detail user', security: [['BearerAuth' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Detail user berhasil diambil', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Detail user berhasil diambil'), new OA\Property(property: 'data', type: 'object')]))])]
#[OA\Post(path: '/api/admin/pinjol', tags: ['Admin'], summary: 'Tambah pinjol', security: [['BearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Pinjol berhasil ditambahkan', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Pinjol berhasil ditambahkan')]))])]
#[OA\Put(path: '/api/admin/pinjol/{id}', tags: ['Admin'], summary: 'Update pinjol', security: [['BearerAuth' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Pinjol berhasil diubah', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Pinjol berhasil diubah')]))])]
#[OA\Delete(path: '/api/admin/pinjol/{id}', tags: ['Admin'], summary: 'Hapus pinjol', security: [['BearerAuth' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Pinjol berhasil dihapus', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Pinjol berhasil dihapus')]))])]
#[OA\Get(path: '/api/admin/laporan/statistik', tags: ['Admin'], summary: 'Statistik laporan', security: [['BearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Statistik laporan berhasil diambil', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Statistik laporan berhasil diambil'), new OA\Property(property: 'data', type: 'object')]))])]
#[OA\Patch(path: '/api/admin/laporan/{id}/status', tags: ['Admin'], summary: 'Update status laporan', security: [['BearerAuth' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Status laporan berhasil diubah', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Status laporan berhasil diubah')]))])]
#[OA\Post(path: '/api/admin/artikel', tags: ['Admin'], summary: 'Tambah artikel', security: [['BearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Artikel berhasil ditambahkan', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Artikel berhasil ditambahkan')]))])]
#[OA\Put(path: '/api/admin/artikel/{id}', tags: ['Admin'], summary: 'Update artikel', security: [['BearerAuth' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Artikel berhasil diubah', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Artikel berhasil diubah')]))])]
#[OA\Delete(path: '/api/admin/artikel/{id}', tags: ['Admin'], summary: 'Hapus artikel', security: [['BearerAuth' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Artikel berhasil dihapus', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Artikel berhasil dihapus')]))])]
#[OA\Post(path: '/api/admin/regulasi', tags: ['Admin'], summary: 'Tambah regulasi', security: [['BearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Regulasi berhasil ditambahkan', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Regulasi berhasil ditambahkan')]))])]
#[OA\Put(path: '/api/admin/regulasi/{id}', tags: ['Admin'], summary: 'Update regulasi', security: [['BearerAuth' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Regulasi berhasil diubah', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Regulasi berhasil diubah')]))])]
#[OA\Delete(path: '/api/admin/regulasi/{id}', tags: ['Admin'], summary: 'Hapus regulasi', security: [['BearerAuth' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Regulasi berhasil dihapus', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Regulasi berhasil dihapus')]))])]
#[OA\Delete(path: '/api/admin/ulasan/{id}', tags: ['Admin'], summary: 'Hapus ulasan', security: [['BearerAuth' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Ulasan berhasil dihapus', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Ulasan berhasil dihapus')]))])]
#[OA\Get(path: '/api/admin/admins', tags: ['Admin'], summary: 'Daftar admin', security: [['BearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Daftar admin berhasil diambil', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Daftar admin berhasil diambil'), new OA\Property(property: 'data', type: 'array', items: new OA\Items(type: 'object'))]))])]
#[OA\Post(path: '/api/admin/admins', tags: ['Admin'], summary: 'Buat admin baru', security: [['BearerAuth' => []]], responses: [new OA\Response(response: 200, description: 'Admin berhasil dibuat', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Admin berhasil dibuat')]))])]
#[OA\Patch(path: '/api/admin/admins/{id}/toggle', tags: ['Admin'], summary: 'Aktif/nonaktifkan admin', security: [['BearerAuth' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Status admin berhasil diubah', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'message', type: 'string', example: 'Status admin berhasil diubah')]))])]
final class AdminEndpoints
{
}
